// Generated by ReScript, PLEASE EDIT WITH CARE

import * as ApolloClient from "rescript-apollo-client/src/ApolloClient.mjs";
import * as ApolloClient__Cache_InMemory_InMemoryCache from "rescript-apollo-client/src/@apollo/client/cache/inmemory/ApolloClient__Cache_InMemory_InMemoryCache.mjs";

var client = ApolloClient.make((function (param) {
        return "http://localhost:4000/graphql\r\n    ";
      }), undefined, undefined, undefined, ApolloClient__Cache_InMemory_InMemoryCache.make(undefined, undefined, undefined, undefined, undefined, undefined), undefined, undefined, true, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined, undefined);

export {
  client ,
  
}
/* client Not a pure module */
