// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Game from "./Game.mjs";
import * as React from "react";
import * as Config from "./Config.mjs";
import * as ViewConfig from "./ViewConfig.mjs";

import './App.css'
;

function App(Props) {
  var match = React.useReducer(Config.reducer, Config.make(undefined));
  var config = match[0];
  return React.createElement(React.Fragment, undefined, React.createElement(ViewConfig.make, {
                  config: config,
                  setConfig: match[1]
                }), React.createElement(Game.make, {
                  config: config
                }));
}

var make = App;

export {
  make ,
  
}
/*  Not a pure module */
