// Generated by ReScript, PLEASE EDIT WITH CARE


function reducer(state, action) {
  switch (action.TAG | 0) {
    case /* FieldSize */0 :
        return {
                field_size: action._0,
                player_size: state.player_size,
                ball_size: state.ball_size
              };
    case /* PlayerSize */1 :
        return {
                field_size: state.field_size,
                player_size: action._0,
                ball_size: state.ball_size
              };
    case /* BallSize */2 :
        return {
                field_size: state.field_size,
                player_size: state.player_size,
                ball_size: action._0
              };
    
  }
}

export {
  reducer ,
  
}
/* No side effect */
