// Generated by ReScript, PLEASE EDIT WITH CARE


function toggleControl(value) {
  if (value === /* NPC */1) {
    return /* Human */0;
  } else {
    return /* NPC */1;
  }
}

function reducer(state, action) {
  if (typeof action === "number") {
    if (action === /* ToggleRightPlayerControl */0) {
      return {
              field_size: state.field_size,
              player_size: state.player_size,
              ball_size: state.ball_size,
              right_player_control: toggleControl(state.right_player_control),
              left_player_control: state.left_player_control
            };
    } else {
      return {
              field_size: state.field_size,
              player_size: state.player_size,
              ball_size: state.ball_size,
              right_player_control: state.right_player_control,
              left_player_control: toggleControl(state.left_player_control)
            };
    }
  }
  switch (action.TAG | 0) {
    case /* SetFieldSize */0 :
        return {
                field_size: action._0,
                player_size: state.player_size,
                ball_size: state.ball_size,
                right_player_control: state.right_player_control,
                left_player_control: state.left_player_control
              };
    case /* SetPlayerSize */1 :
        return {
                field_size: state.field_size,
                player_size: action._0,
                ball_size: state.ball_size,
                right_player_control: state.right_player_control,
                left_player_control: state.left_player_control
              };
    case /* SetBallSize */2 :
        return {
                field_size: state.field_size,
                player_size: state.player_size,
                ball_size: action._0,
                right_player_control: state.right_player_control,
                left_player_control: state.left_player_control
              };
    
  }
}

function make(param) {
  return {
          field_size: 25,
          player_size: 8,
          ball_size: 16,
          right_player_control: /* Human */0,
          left_player_control: /* NPC */1
        };
}

export {
  toggleControl ,
  reducer ,
  make ,
  
}
/* No side effect */
