// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function Game(Props) {
  var config = Props.config;
  return React.createElement(React.Fragment, undefined, String(config.field_size), String(config.player_size), String(config.ball_size));
}

var make = Game;

export {
  make ,
  
}
/* react Not a pure module */
