// Generated by ReScript, PLEASE EDIT WITH CARE

import * as React from "react";

function floatToPx(number) {
  return String(number) + "px";
}

function Message(Props) {
  var children = Props.children;
  var offsetLeft = Props.offsetLeft;
  var offsetTop = Props.offsetTop;
  var limits = Props.limits;
  return React.createElement("div", {
              style: {
                left: String(offsetLeft + limits.right / 2 - 100) + "px",
                position: "absolute",
                textAlign: "center",
                textDecoration: "overline",
                top: String(offsetTop + limits.bottom / 2 + 50) + "px",
                width: "200px"
              }
            }, children);
}

var make = Message;

export {
  floatToPx ,
  make ,
  
}
/* react Not a pure module */
