// Generated by ReScript, PLEASE EDIT WITH CARE


var keys = {
  arrowUp: false,
  arrowDown: false
};

var ballVectorTable = [
  [
    5,
    0.3
  ],
  [
    4,
    1.2
  ],
  [
    3,
    2
  ],
  [
    0,
    0
  ]
];

function init(config) {
  var fieldWidth = Math.imul(config.field_size, 22);
  var fieldHeight = config.field_size / 30 * 440;
  var playerSize = Math.imul(config.player_size, 10);
  var leftPlayerY = (fieldHeight - playerSize) / 2;
  var rightPlayerY = (fieldHeight - playerSize) / 2;
  var rightPlayerX = fieldWidth - 14;
  var ballSize = config.ball_size;
  var ballX = (fieldWidth - ballSize) / 2;
  var ballY = (fieldHeight - ballSize) / 2;
  return {
          offsetLeft: 300,
          offsetTop: 50,
          fieldWidth: fieldWidth,
          fieldHeight: fieldHeight,
          playerSize: playerSize,
          playerWidth: 14,
          leftPlayerX: 0,
          leftPlayerY: leftPlayerY,
          rightPlayerX: rightPlayerX,
          rightPlayerY: rightPlayerY,
          leftPlayerCenterX: 0 + 14 / 2,
          rightPlayerCenterX: rightPlayerX + 14 / 2,
          ballSize: ballSize,
          ballX: ballX,
          ballY: ballY
        };
}

function make(param) {
  return {
          rightPlayerY: param.rightPlayerY,
          leftPlayerY: param.leftPlayerY,
          playerWidth: param.playerWidth,
          keys: keys,
          game: /* Paused */2,
          horizontalCollision: undefined,
          ball: {
            x: param.ballX,
            y: param.ballY,
            size: param.ballSize,
            speed: 0.8,
            horizontalDirection: /* Left */0,
            verticalDirection: /* Down */0,
            vectorIndex: 1
          },
          fieldLimits: {
            bottom: param.fieldHeight,
            right: param.fieldWidth
          },
          playerSize: param.playerSize,
          oldTime: 0
        };
}

export {
  keys ,
  ballVectorTable ,
  init ,
  make ,
  
}
/* No side effect */
