// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";

function ViewConfig$Slider(Props) {
  var value = Props.value;
  var label = Props.label;
  var max = Props.max;
  var min = Props.min;
  var onChange = Props.onChange;
  return React.createElement(React.Fragment, undefined, React.createElement("tr", undefined, React.createElement("td", {
                      style: {
                        paddingTop: "20px"
                      }
                    }, label)), React.createElement("tr", undefined, React.createElement("td", undefined, React.createElement("input", {
                          max: max,
                          min: min,
                          type: "range",
                          value: value,
                          onChange: onChange
                        })), React.createElement("td", undefined, value)));
}

var Slider = {
  make: ViewConfig$Slider
};

function ViewConfig(Props) {
  var config = Props.config;
  var setConfig = Props.setConfig;
  return React.createElement("div", {
              className: "configContainer"
            }, React.createElement("fieldset", undefined, React.createElement("legend", undefined, "Config"), React.createElement("table", undefined, React.createElement("tbody", undefined, React.createElement(ViewConfig$Slider, {
                              value: String(config.field_size),
                              label: "Field size",
                              max: "40",
                              min: "10",
                              onChange: (function (evt) {
                                  return Curry._1(setConfig, {
                                              TAG: /* SetFieldSize */0,
                                              _0: evt.target.value
                                            });
                                })
                            }), React.createElement(ViewConfig$Slider, {
                              value: String(config.player_size),
                              label: "Player size",
                              max: "20",
                              min: "6",
                              onChange: (function (evt) {
                                  return Curry._1(setConfig, {
                                              TAG: /* SetPlayerSize */1,
                                              _0: evt.target.value
                                            });
                                })
                            }), React.createElement(ViewConfig$Slider, {
                              value: String(config.ball_size),
                              label: "Ball size",
                              max: "30",
                              min: "6",
                              onChange: (function (evt) {
                                  return Curry._1(setConfig, {
                                              TAG: /* SetBallSize */2,
                                              _0: evt.target.value
                                            });
                                })
                            })))));
}

var make = ViewConfig;

export {
  Slider ,
  make ,
  
}
/* react Not a pure module */
