// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as React from "react";

function ViewConfigUI$Slider(Props) {
  var value = Props.value;
  var label = Props.label;
  var max = Props.max;
  var min = Props.min;
  var onChange = Props.onChange;
  return React.createElement(React.Fragment, undefined, React.createElement("tr", undefined, React.createElement("td", undefined, label)), React.createElement("tr", undefined, React.createElement("td", {
                      style: {
                        paddingBottom: "20px"
                      }
                    }, React.createElement("input", {
                          max: max,
                          min: min,
                          type: "range",
                          value: value,
                          onChange: onChange
                        })), React.createElement("td", {
                      style: {
                        paddingBottom: "20px"
                      }
                    }, value)));
}

var Slider = {
  make: ViewConfigUI$Slider
};

function ViewConfigUI(Props) {
  var config = Props.config;
  var setConfig = Props.setConfig;
  return React.createElement("fieldset", undefined, React.createElement("legend", undefined, "Configuration"), React.createElement("table", undefined, React.createElement("tbody", undefined, React.createElement(ViewConfigUI$Slider, {
                          value: String(config.field_size),
                          label: "Field size",
                          max: "40",
                          min: "10",
                          onChange: (function (evt) {
                              return Curry._1(setConfig, {
                                          TAG: /* FieldSize */0,
                                          _0: evt.target.value
                                        });
                            })
                        }), React.createElement(ViewConfigUI$Slider, {
                          value: String(config.player_size),
                          label: "Player size",
                          max: "20",
                          min: "6",
                          onChange: (function (evt) {
                              return Curry._1(setConfig, {
                                          TAG: /* PlayerSize */1,
                                          _0: evt.target.value
                                        });
                            })
                        }), React.createElement(ViewConfigUI$Slider, {
                          value: String(config.ball_size),
                          label: "Ball size",
                          max: "30",
                          min: "6",
                          onChange: (function (evt) {
                              return Curry._1(setConfig, {
                                          TAG: /* BallSize */2,
                                          _0: evt.target.value
                                        });
                            })
                        }))));
}

var make = ViewConfigUI;

export {
  Slider ,
  make ,
  
}
/* react Not a pure module */
