// Generated by ReScript, PLEASE EDIT WITH CARE

import * as Curry from "rescript/lib/es6/curry.js";
import * as Model from "./Model.mjs";
import * as React from "react";
import * as Update from "./Update.mjs";

function intToPx(number) {
  return String(number) + "px";
}

function keyEventHandler(evt, dispatch) {
  var match = evt.key;
  switch (match) {
    case " " :
        evt.preventDefault();
        if (evt.type === "keydown") {
          return Curry._1(dispatch, /* KeyEvent */{
                      _0: evt.type,
                      _1: evt.key
                    });
        } else {
          return ;
        }
    case "ArrowDown" :
    case "ArrowUp" :
        break;
    default:
      return ;
  }
  evt.preventDefault();
  return Curry._1(dispatch, /* KeyEvent */{
              _0: evt.type,
              _1: evt.key
            });
}

function ViewGame(Props) {
  var config = Props.config;
  var match = Model.init(config);
  var ballY = match.ballY;
  var ballX = match.ballX;
  var ballSize = match.ballSize;
  var playerWidth = match.playerWidth;
  var playerSize = match.playerSize;
  var offsetTop = match.offsetTop;
  var offsetLeft = match.offsetLeft;
  var match$1 = React.useReducer(Update.updateState, Model.make(match.rightPlayerY, ballX, ballY, ballSize));
  var dispatch = match$1[1];
  var state = match$1[0];
  React.useEffect((function () {
          document.addEventListener("keydown", (function (evt) {
                  return keyEventHandler(evt, dispatch);
                }));
          document.addEventListener("keyup", (function (evt) {
                  return keyEventHandler(evt, dispatch);
                }));
          return (function (param) {
                    document.removeEventListener("keyup");
                    document.removeEventListener("keydown");
                    
                  });
        }), []);
  return React.createElement(React.Fragment, undefined, React.createElement("div", {
                  className: "field",
                  style: {
                    height: String(match.fieldHeight) + "px",
                    left: String(offsetLeft) + "px",
                    top: String(offsetTop) + "px",
                    width: String(match.fieldWidth) + "px"
                  }
                }), React.createElement("div", {
                  className: "player",
                  style: {
                    height: String(playerSize) + "px",
                    left: String(match.leftPlayerX + offsetLeft | 0) + "px",
                    top: String(match.leftPlayerY + offsetTop | 0) + "px",
                    width: String(playerWidth) + "px"
                  }
                }), React.createElement("div", {
                  className: "player",
                  style: {
                    height: String(playerSize) + "px",
                    left: String(match.rightPlayerX + offsetLeft | 0) + "px",
                    top: String(state.rightPlayerY + offsetTop | 0) + "px",
                    width: String(playerWidth) + "px"
                  }
                }), React.createElement("div", {
                  className: "ball",
                  style: {
                    height: String(ballSize) + "px",
                    left: String(ballX + offsetLeft | 0) + "px",
                    top: String(ballY + offsetTop | 0) + "px",
                    width: String(ballSize) + "px",
                    borderRadius: String(ballSize / 2 | 0) + "px"
                  }
                }), React.createElement(Update.Tick.make, {
                  state: state,
                  dispatch: dispatch
                }));
}

var make = ViewGame;

export {
  intToPx ,
  keyEventHandler ,
  make ,
  
}
/* react Not a pure module */
